name: Java CI with Ant

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to v4 for Node.js 20 support

      - name: Set up JDK 11
        uses: actions/setup-java@v3 # Update to v3 for Node.js 20 support
        with:
          java-version: "11"

      - name: Install Ant
        run: sudo apt-get install -y ant

      - name: Build with Ant
        run: ant -noinput -buildfile build.xml # Ensure this path is correct
